region_read:
  path: /region/{module}/{id}
  defaults:
    _controller: "RegionEntity:Region:read"
    _scope: frontend
    _token_check: false
    id: null
  requirements:
    version: '\d+'
  methods: [GET]
